services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_WEB_APP_URL=http://localhost:8080/
        - REACT_APP_SIMPLIFY_API=http://localhost:8080/api/v1/scrum
    ports:
      - "3000:80"
     